import{describe,it,expect,vi}from'vitest';import{connect}from'@thenavidm/slipway/testing';import{CloudflareClient}from'../src/api/client.js';import{loadConfig}from'../src/config.js';import{createApp}from'../src/app.js';import{ALL_TOOLS,compileAll}from'../src/tools/index.js';import{mkdtemp,writeFile,chmod,symlink}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
const zone='a'.repeat(32),record='b'.repeat(32);const dns={name:'review.example.com',type:'A',content:'192.0.2.1',ttl:1,proxied:false};const ok=(x:unknown={id:record})=>new Response(JSON.stringify({success:true,result:x}),{headers:{'content-type':'application/json'}});
// The real Slipway server with an injected client. A call to a hidden tool is a protocol error rather than a tool result; both are refusals a client sees.
async function fixture(env:NodeJS.ProcessEnv={},fetcher:any=vi.fn(async()=>ok())){const settings={CLOUDFLARE_API_TOKEN:'fixture-token',CLOUDFLARE_MIN_REQUEST_INTERVAL_MS:'0',...env};const config=loadConfig(settings);const api=new CloudflareClient(config,fetcher);const mcp=await connect(createApp({context:()=>({config,client:api})}),{env:settings});const c={listTools:async()=>({tools:await mcp.listTools()}),callTool:async({name,arguments:args}:{name:string;arguments:Record<string,unknown>}):Promise<any>=>{try{return await mcp.callTool(name,args);}catch(e){return{isError:true,content:[{type:'text',text:JSON.stringify({error:(e as Error).message})}]};}}};return{c,api,fetcher,close:()=>mcp.close()};}
const text=(r:any)=>JSON.stringify(r);
// Slipway's errors are JSON; an argument the MCP SDK rejects first comes back as its own plain text.
const value=(r:any)=>{try{return JSON.parse(r.content[0].text);}catch{return{error:r.content[0].text};}};
describe('current Cloudflare account workflows',()=>{
 it('compiles every input and body schema with the native validator',()=>expect(compileAll()).toBeGreaterThan(ALL_TOOLS.length));
 it('confirms creates before native file/network work',async()=>{const f=await fixture();try{const r=await f.c.callTool({name:'create_dns_record',arguments:{zone_id:zone,payload_file:'/missing/approved.json'}});expect(r.isError).toBe(true);expect(text(r)).toContain('confirm');expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('sends the exact approved native body once to the fixed origin',async()=>{const f=await fixture();try{const r=await f.c.callTool({name:'create_dns_record',arguments:{zone_id:zone,payload:dns,confirm:true}});expect(r.isError).not.toBe(true);expect(f.fetcher).toHaveBeenCalledTimes(1);const[url,init]=f.fetcher.mock.calls[0];expect(url.toString()).toBe('https://api.cloudflare.com/client/v4/zones/'+zone+'/dns_records');expect(JSON.parse(init.body)).toEqual(dns);expect(init.headers.Authorization).toBe('Bearer fixture-token');expect(init.redirect).toBe('error');}finally{await f.close();}});
 it('hides writes and refuses confirmed direct calls in read-only mode',async()=>{const f=await fixture({CLOUDFLARE_READ_ONLY:'1'});try{expect((await f.c.listTools()).tools.length).toBe(18);const r=await f.c.callTool({name:'create_dns_record',arguments:{zone_id:zone,payload:dns,confirm:true}});expect(r.isError).toBe(true);expect(text(r)).toMatch(/READ_ONLY|not found/);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('disabled mutations refuse confirmation',async()=>{const f=await fixture({CLOUDFLARE_ALLOW_DESTRUCTIVE:'0'});try{const r=await f.c.callTool({name:'delete_dns_record',arguments:{zone_id:zone,dns_record_id:record,confirm:true}});expect(r.isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('rejects unknown native root fields before fetch',async()=>{const f=await fixture();try{const r=await f.c.callTool({name:'create_dns_record',arguments:{zone_id:zone,payload:{...dns,proxeid:true},confirm:true}});expect(r.isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('preserves source DNS type unions and fails invalid IP content',async()=>{const f=await fixture();try{const r=await f.c.callTool({name:'create_dns_record',arguments:{zone_id:zone,payload:{...dns,content:'not-an-ip'},confirm:true}});expect(r.isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('rejects competing payload routes',async()=>{const f=await fixture();try{const r=await f.c.callTool({name:'create_dns_record',arguments:{zone_id:zone,payload:dns,payload_file:'/missing.json',confirm:true}});expect(r.isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('previews locally without credentials even in read-only mode',async()=>{const f=await fixture({CLOUDFLARE_API_TOKEN:undefined,CLOUDFLARE_READ_ONLY:'1'});try{const r=await f.c.callTool({name:'preview_operation',arguments:{operation:'create_dns_record',arguments:{zone_id:zone,payload:dns}}});expect(value(r)).toMatchObject({method:'POST',body:dns,localOnly:true,providerValidated:false});expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('requires a target instead of sending missing profile defaults',async()=>{const f=await fixture();try{const r=await f.c.callTool({name:'get_zone',arguments:{}});expect(r.isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('uses selected profile defaults and preserves explicit zone IDs',async()=>{const f=await fixture({CLOUDFLARE_ACCOUNTS:JSON.stringify([{name:'work',api_token:'work-fixture',zone_id:zone}]),CLOUDFLARE_API_TOKEN:'global-never-use'});try{await f.c.callTool({name:'get_zone',arguments:{}});await f.c.callTool({name:'get_zone',arguments:{zone_id:record}});expect(f.fetcher.mock.calls.map((x:any)=>x[0].pathname)).toEqual(['/client/v4/zones/'+zone,'/client/v4/zones/'+record]);expect(f.fetcher.mock.calls[0][1].headers.Authorization).toBe('Bearer work-fixture');}finally{await f.close();}});
 it('does not borrow global auth or IDs for an empty named profile',async()=>{const f=await fixture({CLOUDFLARE_ACCOUNTS:JSON.stringify([{name:'empty'}]),CLOUDFLARE_ZONE_ID:zone});try{const r=await f.c.callTool({name:'get_zone',arguments:{zone_id:zone}});expect(r.isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('rejects malformed profiles, duplicate labels and unknown defaults',()=>{expect(()=>loadConfig({CLOUDFLARE_ACCOUNTS:'[{"name":"x"},{"name":"x"}]'})).toThrow();expect(()=>loadConfig({CLOUDFLARE_ACCOUNTS:'[{"name":"x","token_file":42}]'})).toThrow();expect(()=>loadConfig({CLOUDFLARE_DEFAULT_ACCOUNT:'missing'})).toThrow();});
 it('returns native source schemas without auth or network',async()=>{const f=await fixture({CLOUDFLARE_API_TOKEN:undefined});try{const r=await f.c.callTool({name:'get_operation_schema',arguments:{operation:'create_dns_record'}});expect(value(r).body.$defs).toBeTruthy();expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('rejects unsafe encoded path separators and alternate origins',async()=>{const f=await fixture();try{await expect(f.api.request('GET','//example.com')).rejects.toThrow();await expect(f.api.request('GET','/zones/a%2fb')).rejects.toThrow();expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('fails HTTP 200 envelope errors and redacts echoed credentials',async()=>{const f=await fixture({},vi.fn(async()=>new Response(JSON.stringify({success:false,errors:[{message:'fixture-token',api_key:'fixture-token'}]}))));try{const r=await f.c.callTool({name:'get_zone',arguments:{zone_id:zone}});expect(r.isError).toBe(true);expect(text(r)).not.toContain('fixture-token');}finally{await f.close();}});
 it('does not retry 429 creates or reads',async()=>{const fetcher=vi.fn(async()=>new Response('{"errors":[]}',{status:429,headers:{'retry-after':'0'}}));const f=await fixture({},fetcher);try{await f.c.callTool({name:'create_dns_record',arguments:{zone_id:zone,payload:dns,confirm:true}});await f.c.callTool({name:'get_zone',arguments:{zone_id:zone}});expect(fetcher).toHaveBeenCalledTimes(2);}finally{await f.close();}});
 it('does not replay unknown network outcomes',async()=>{const fetcher=vi.fn(async()=>{throw Error('network');});const f=await fixture({},fetcher);try{await f.c.callTool({name:'create_dns_record',arguments:{zone_id:zone,payload:dns,confirm:true}});expect(fetcher).toHaveBeenCalledTimes(1);}finally{await f.close();}});
 it('bounds streamed responses',async()=>{const f=await fixture({},vi.fn(async()=>new Response('x'.repeat(5*1024*1024+1))));try{const r=await f.c.callTool({name:'get_zone',arguments:{zone_id:zone}});expect(r.isError).toBe(true);expect(text(r)).toContain('local cap');expect(f.fetcher).toHaveBeenCalledTimes(1);}finally{await f.close();}});
 it('accepts a regular private token file and refuses its symlink',async()=>{const dir=await mkdtemp(join(tmpdir(),'cf-token-fixture-'));const path=join(dir,'token');await writeFile(path,'file-fixture',{mode:0o600});const f=await fixture({CLOUDFLARE_TOKEN_FILE:path});try{await f.c.callTool({name:'get_zone',arguments:{zone_id:zone}});expect(f.fetcher.mock.calls[0][1].headers.Authorization).toBe('Bearer file-fixture');}finally{await f.close();}const alias=join(dir,'link');await symlink(path,alias);const g=await fixture({CLOUDFLARE_TOKEN_FILE:alias});try{expect((await g.c.callTool({name:'get_zone',arguments:{zone_id:zone}})).isError).toBe(true);expect(g.fetcher).not.toHaveBeenCalled();}finally{await g.close();}});
 it.skipIf(process.platform==='win32')('refuses broadly readable POSIX token files',async()=>{const dir=await mkdtemp(join(tmpdir(),'cf-mode-fixture-'));const path=join(dir,'token');await writeFile(path,'file-fixture');await chmod(path,0o644);const f=await fixture({CLOUDFLARE_TOKEN_FILE:path});try{expect((await f.c.callTool({name:'get_zone',arguments:{zone_id:zone}})).isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
});
describe('reviewed DNS batches and bounded reads',()=>{
 it('binds a review to exact native body/zone/profile and submits once',async()=>{const f=await fixture();try{const input={zone_id:zone,payload:{posts:[dns]}};const p=value(await f.c.callTool({name:'preview_dns_batch',arguments:input}));expect(p.localOnly).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();const r=await f.c.callTool({name:'apply_dns_batch',arguments:{...input,preview_sha256:p.preview_sha256,confirm:true}});expect(r.isError).not.toBe(true);expect(f.fetcher).toHaveBeenCalledTimes(1);expect(JSON.parse(f.fetcher.mock.calls[0][1].body)).toEqual(input.payload);}finally{await f.close();}});
 it('fails changed reviewed inputs before any request',async()=>{const f=await fixture();try{const input={zone_id:zone,payload:{posts:[dns]}};const p=value(await f.c.callTool({name:'preview_dns_batch',arguments:input}));const r=await f.c.callTool({name:'apply_dns_batch',arguments:{...input,zone_id:record,preview_sha256:p.preview_sha256,confirm:true}});expect(r.isError).toBe(true);expect(text(r)).toContain('changed');expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('refuses empty and oversized reviewed batches locally',async()=>{const f=await fixture();try{for(const payload of [{posts:[]},{posts:Array(51).fill(dns)}]){const r=await f.c.callTool({name:'preview_dns_batch',arguments:{zone_id:zone,payload}});expect(r.isError).toBe(true);}expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('does not make the digest an approval or read-only bypass',async()=>{const f=await fixture({CLOUDFLARE_READ_ONLY:'1'});try{const input={zone_id:zone,payload:{posts:[dns]}};const p=value(await f.c.callTool({name:'preview_dns_batch',arguments:input}));expect((await f.c.callTool({name:'apply_dns_batch',arguments:{...input,preview_sha256:p.preview_sha256,confirm:true}})).isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('caps pagination and returns an explicit resume page',async()=>{const f=await fixture({},vi.fn(async()=>new Response(JSON.stringify({success:true,result:[],result_info:{total_pages:4}}))));try{const r=value(await f.c.callTool({name:'query_pages',arguments:{operation:'list_dns_records',arguments:{zone_id:zone,per_page:10},max_pages:2}}));expect(r).toMatchObject({pagesRead:2,hasMore:true,resumePage:3,continuationUnknown:false});expect(f.fetcher.mock.calls.map((x:any)=>x[0].searchParams.get('page'))).toEqual(['1','2']);}finally{await f.close();}});
 it('stops on unknown pagination metadata instead of claiming completion',async()=>{const f=await fixture();try{const r=value(await f.c.callTool({name:'query_pages',arguments:{operation:'list_zones',arguments:{},max_pages:5}}));expect(r).toMatchObject({pagesRead:1,continuationUnknown:true});expect(f.fetcher).toHaveBeenCalledTimes(1);}finally{await f.close();}});
 it('stops remaining pages after an API error',async()=>{const f=await fixture({},vi.fn(async()=>new Response(JSON.stringify({success:false,errors:[]}))));try{const r=await f.c.callTool({name:'query_pages',arguments:{operation:'list_zones',arguments:{},max_pages:5}});expect(r.isError).toBe(true);expect(f.fetcher).toHaveBeenCalledTimes(1);}finally{await f.close();}});
 it('refuses mutation and excessive page budgets preflight',async()=>{const f=await fixture();try{for(const args of[{operation:'create_dns_record',arguments:{zone_id:zone,payload:dns},max_pages:1},{operation:'list_zones',arguments:{},max_pages:6}])expect((await f.c.callTool({name:'query_pages',arguments:args})).isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('allows one parsed analytics query and preserves variables',async()=>{const f=await fixture({},vi.fn(async()=>new Response(JSON.stringify({data:{viewer:{zones:[]}}}))));try{const query='query Q($zone: String!){viewer{zones(filter:{zoneTag:$zone}){__typename}}}';const r=await f.c.callTool({name:'analytics_query',arguments:{query,variables:{zone}}});expect(r.isError).not.toBe(true);expect(JSON.parse(f.fetcher.mock.calls[0][1].body)).toEqual({query,variables:{zone}});}finally{await f.close();}});
 it('rejects analytics mutations, subscriptions and multiple operations',async()=>{const f=await fixture({CLOUDFLARE_READ_ONLY:'1'});try{for(const query of ['mutation {deleteZone}','subscription {events}','query A{viewer{__typename}} query B{viewer{__typename}}'])expect((await f.c.callTool({name:'analytics_query',arguments:{query}})).isError).toBe(true);expect(f.fetcher).not.toHaveBeenCalled();}finally{await f.close();}});
 it('fails partial GraphQL errors instead of returning misleading success',async()=>{const f=await fixture({},vi.fn(async()=>new Response(JSON.stringify({data:{viewer:{}},errors:[{message:'fixture-token'}]}))));try{const r=await f.c.callTool({name:'analytics_query',arguments:{query:'{viewer{__typename}}'}});expect(r.isError).toBe(true);expect(text(r)).not.toContain('fixture-token');}finally{await f.close();}});
 it('retains ordinary URLs and redacts configured secrets/credential URLs',async()=>{const f=await fixture();try{expect(f.api.sanitize({url:'https://example.com/photo.jpg',credential:'https://example.com/file?token=private',text:'fixture-token',authorization:'private'})).toEqual({url:'https://example.com/photo.jpg',credential:'[private credential URL]',text:'[redacted]',authorization:'[redacted]'});}finally{await f.close();}});
});
