export type Account = {name:string;apiToken:string;tokenFile:string;accountId:string;zoneId:string;tokenKind:"user"|"account"};
export type Config = {accounts:Account[];defaultAccount:string;readOnly:boolean;allowDestructive:boolean;auditPath:string;timeoutMs:number;minIntervalMs:number};
function integer(v:string|undefined,defaultValue:number,min:number,max:number):number{const n=v?Number(v):defaultValue;if(!Number.isInteger(n)||n<min||n>max)throw Error('Invalid request timeout or pacing settings.');return n;}
export function loadConfig(env:NodeJS.ProcessEnv=process.env):Config{
 let entries:Record<string,unknown>[]=[];
 if(env.CLOUDFLARE_ACCOUNTS){try{const v=JSON.parse(env.CLOUDFLARE_ACCOUNTS);if(!Array.isArray(v))throw Error();entries=v;}catch{throw Error('CLOUDFLARE_ACCOUNTS must be a private JSON array of named accounts.');}}
 else if(env.CLOUDFLARE_API_TOKEN||env.CLOUDFLARE_TOKEN_FILE)entries=[{name:'default',api_key:env.CLOUDFLARE_API_TOKEN,token_file:env.CLOUDFLARE_TOKEN_FILE,account_id:env.CLOUDFLARE_ACCOUNT_ID,zone_id:env.CLOUDFLARE_ZONE_ID,token_kind:env.CLOUDFLARE_TOKEN_KIND}];
 const accounts=entries.map(x=>{if(!x||typeof x!=='object'||typeof x.name!=='string'||!x.name.trim())throw Error('Every Cloudflare account requires a unique nonempty name.');for(const k of ['api_key','api_token','token_file','account_id','zone_id','token_kind'])if(x[k]!==undefined&&(typeof x[k]!=='string'||/[\r\n]/.test(x[k] as string)))throw Error('Private Cloudflare profile settings must be strings without line breaks.');if(x.token_kind!==undefined&&x.token_kind!==''&&!['user','account'].includes(x.token_kind as string))throw Error('token_kind must be user or account.');return {name:x.name.trim(),apiToken:String(x.api_key??x.api_token??''),tokenFile:String(x.token_file??''),accountId:String(x.account_id??''),zoneId:String(x.zone_id??''),tokenKind:(x.token_kind||'user') as 'user'|'account'};});
 if(new Set(accounts.map(a=>a.name)).size!==accounts.length)throw Error('Cloudflare account names must be unique.');
 const defaultAccount=env.CLOUDFLARE_DEFAULT_ACCOUNT??accounts[0]?.name??'';if(defaultAccount&&!accounts.some(a=>a.name===defaultAccount))throw Error('Unknown account configured as CLOUDFLARE_DEFAULT_ACCOUNT.');
 return {accounts,defaultAccount,readOnly:/^(1|true)$/i.test(env.CLOUDFLARE_READ_ONLY??''),allowDestructive:!/^(0|false)$/i.test(env.CLOUDFLARE_ALLOW_DESTRUCTIVE??''),auditPath:env.CLOUDFLARE_AUDIT_LOG??'',timeoutMs:integer(env.CLOUDFLARE_REQUEST_TIMEOUT_MS,30000,100,300000),minIntervalMs:integer(env.CLOUDFLARE_MIN_REQUEST_INTERVAL_MS,200,0,10000)};
}
export function selectAccount(config:Config,hint?:string):Account{const a=config.accounts.find(a=>a.name===(hint??config.defaultAccount));if(!a)throw Error(config.accounts.length?'Unknown account. Run list_accounts and use its exact name.':'No credentials configured. Set CLOUDFLARE_API_TOKEN or CLOUDFLARE_TOKEN_FILE privately; run cloudflare-cli login.');return a;}
