import operationsData from './operations.json' with {type:'json'};
import {Ajv2020} from 'ajv/dist/2020.js';import type{ValidateFunction}from'ajv';import addFormats from'ajv-formats';
import{readFile,lstat}from'node:fs/promises';import{createHash}from'node:crypto';import{parse,Kind}from'graphql';
import type{Json,CloudflareClient,QueryParam}from'../api/client.js';import{UsageError}from'../api/errors.js';import type{Config}from'../config.js';import type{Risk}from'../safety.js';
export type Operation={name:string;title:string;description:string;operationId:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json;style?:string;explode?:boolean}[];bodySchema:Json;bodyRequired:boolean;paginated:boolean;origin:'api';contentType:string};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:CloudflareClient)=>Promise<unknown>};
export const OPERATIONS=operationsData as unknown as Operation[];
const ajv=new Ajv2020({allErrors:true,strict:false});(addFormats as unknown as(a:typeof ajv)=>void)(ajv);
function check(v:ValidateFunction,x:unknown){if(!v(x))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
const validators=new Map<string,ValidateFunction>();const bodyValidators=new Map(OPERATIONS.map(o=>[o.name,ajv.compile(o.bodySchema)]));
function fieldsFor(o:Operation):Json{const properties:Json=Object.fromEntries(o.params.map(p=>[p.key,p.schema]));properties.account={type:'string',description:'Exact private profile label. Account/zone defaults route inputs; token permissions remain provider controlled.'};if(o.risk!=='read')properties.confirm={type:'boolean',description:'Must be true for the exact selected mutation, target and reviewed request.'};if(o.bodyRequired){properties.payload={...o.bodySchema,description:'Complete current native JSON request body. Do not mix with payload_file.'};properties.payload_file={type:'string',minLength:1,description:'Regular non-symlink local JSON request file, at most 1 MiB. No credentials in public files.'};}return{type:'object',$defs:o.bodySchema.$defs,properties,required:o.params.filter(p=>p.required&&!['zone_id','account_id'].includes(p.key)).map(p=>p.key),additionalProperties:false};}
function native(o:string){const op=OPERATIONS.find(p=>p.name===o);if(!op)throw new UsageError('Unknown named operation; use get_operation_schema.');return op;}
export async function prepare(o:Operation,args:Json,client:CloudflareClient){
 if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');
 let body:Json=args.payload??{};
 if(args.payload_file){try{const stat=await lstat(args.payload_file);if(!stat.isFile()||stat.size>1024*1024)throw Error();body=JSON.parse(await readFile(args.payload_file,'utf8'));}catch{throw new UsageError('payload_file must be a regular non-symlink JSON file, at most 1 MiB.');}}
 if(o.bodyRequired&&args.payload===undefined&&args.payload_file===undefined)throw new UsageError('Provide the complete native JSON body with payload or payload_file.');
 check(bodyValidators.get(o.name)!,body);
 const profile=client.config.accounts.find(a=>a.name===(args.account??client.config.defaultAccount));
 const values={...args};for(const p of o.params){if(values[p.key]===undefined){if(p.key==='account_id'&&profile?.accountId)values[p.key]=profile.accountId;if(p.key==='zone_id'&&profile?.zoneId)values[p.key]=profile.zoneId;}if(p.required&&values[p.key]===undefined)throw new UsageError('Missing required argument: '+p.key+'; use an explicit ID or the selected private profile default.');if(values[p.key]!==undefined){const v=ajv.compile({...p.schema,$defs:o.bodySchema.$defs});check(v,values[p.key]);}}
 const path=o.params.filter(p=>p.in==='path').reduce((path,p)=>path.replace('{'+p.name+'}',encodeURIComponent(String(values[p.key]))),o.path);
 const query:QueryParam[]=o.params.filter(p=>p.in==='query'&&values[p.key]!==undefined).map(p=>({name:p.name,value:values[p.key],style:p.style,explode:p.explode}));
 return {path,query,body:o.bodyRequired?body:undefined,account:args.account??client.config.defaultAccount??'default'};
}
async function execute(o:Operation,args:Json,client:CloudflareClient){const p=await prepare(o,args,client);return client.request(o.method,p.path,p.query,p.body,args.account);}
export const ALL_TOOLS:ToolSpec[]=OPERATIONS.map(o=>({name:o.name,title:o.title,description:o.description+'\n'+(o.risk==='read'?'Read operation.':'Every change requires explicit confirmation; never repeat an unknown outcome automatically.'),group:o.group,inputSchema:fieldsFor(o),risk:o.risk,handler:(a,c)=>execute(o,a,c)}));
const obj=(properties:Json,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
ALL_TOOLS.push({name:'list_accounts',title:'List private profiles',description:'Local profile labels/default/auth method only. No provider IDs, credential values or paths. No network.',group:'Local',risk:'read',inputSchema:obj({}),handler:async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,auth:a.tokenFile?'token_file':a.apiToken?'api_token':'not_configured'}))})});
ALL_TOOLS.push({name:'get_operation_schema',title:'Inspect native schema',description:'Complete selected current API input, path and query schema. Local metadata only.',group:'Local',risk:'read',inputSchema:obj({operation:{type:'string',enum:OPERATIONS.map(o=>o.name)}},['operation']),handler:async a=>{const o=native(a.operation);return{operation:o.name,operationId:o.operationId,method:o.method,path:o.path,parameters:o.params,body:o.bodySchema,paginated:o.paginated};}});
ALL_TOOLS.push({name:'preview_operation',title:'Preview selected request',description:'Validate a named operation and return its exact local method/path/query/body/profile. No request, auth validation or provider policy checks.',group:'Local',risk:'read',inputSchema:obj({operation:{type:'string',enum:OPERATIONS.map(o=>o.name)},arguments:{type:'object'}},['operation','arguments']),handler:async(a,c)=>{const o=native(a.operation);validateArguments(ALL_TOOLS.find(t=>t.name===o.name)!,a.arguments);return{operation:o.name,method:o.method,...await prepare(o,a.arguments,c),localOnly:true,providerValidated:false};}});
ALL_TOOLS.push({name:'query_pages',title:'Bounded native pages',description:'Read at most five pages of a supported paginated named operation. Provider page metadata determines continuation; missing metadata stops with an explicit unknown continuation.',group:'Reads',risk:'read',inputSchema:obj({operation:{type:'string',enum:OPERATIONS.filter(o=>o.risk==='read'&&o.paginated).map(o=>o.name)},arguments:{type:'object'},max_pages:{type:'integer',minimum:1,maximum:5,default:1}},['operation','arguments']),handler:async(a,c)=>{const o=native(a.operation);if(o.risk!=='read'||!o.paginated)throw new UsageError('Use a named supported paginated read.');validateArguments(ALL_TOOLS.find(t=>t.name===o.name)!,a.arguments);let page=a.arguments.page??1;const per_page=a.arguments.per_page??50;if(!Number.isInteger(page)||page<1||!Number.isInteger(per_page)||per_page<1||per_page>100)throw new UsageError('Bounded pagination requires positive integer page and per_page between 1 and 100.');const pages=[];let hasMore=false,unknown=false;for(let n=0;n<(a.max_pages??1);n++){const result=await execute(o,{...a.arguments,page,per_page},c)as Json;pages.push(result);const i=result.result_info;if(Number.isInteger(i?.total_pages))hasMore=page<i.total_pages;else if(Number.isInteger(i?.total_count))hasMore=page*per_page<i.total_count;else{unknown=true;hasMore=false;}if(!hasMore)break;page++;}return{pages,pagesRead:pages.length,hasMore,continuationUnknown:unknown,resumePage:hasMore?page:undefined};}});
const batch=native('batch_dns_records');const batchFields:Json={zone_id:{type:'string',minLength:1,maxLength:32},account:{type:'string'},payload:batch.bodySchema,payload_file:{type:'string',minLength:1}};
function canonical(v:unknown):string{if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical((v as Json)[k])).join(',')+'}';return JSON.stringify(v);}
async function batchPlan(a:Json,c:CloudflareClient){const{confirm,preview_sha256,...nativeArgs}=a;validateArguments(ALL_TOOLS.find(t=>t.name===batch.name)!,nativeArgs);const p=await prepare(batch,nativeArgs,c);const body=p.body!;const count=['deletes','patches','puts','posts'].reduce((n,k)=>n+(Array.isArray(body[k])?body[k].length:0),0);if(!count||count>50)throw new UsageError('Reviewed DNS batch must contain between 1 and 50 total actions.');const account=(a.account??c.config.defaultAccount)||'default';const plan={method:batch.method,path:p.path,profile:account,body};return{...plan,actions:count,preview_sha256:createHash('sha256').update(canonical(plan)).digest('hex'),localOnly:true,providerValidated:false};}
ALL_TOOLS.push({name:'preview_dns_batch',title:'Review DNS batch',description:'Local schema-validated DNS batch review capped at 50 actions. Digest binds exact JSON body, zone path and profile label; no account or DNS state read. Not a provider authorization grant.',group:'DNS review',risk:'read',inputSchema:{...obj(batchFields),$defs:batch.bodySchema.$defs},handler:batchPlan});
ALL_TOOLS.push({name:'apply_dns_batch',title:'Apply reviewed DNS batch',description:'Verify the reviewed digest and submit one exact native DNS batch with mandatory confirmation. Does not assert remote-state consistency or atomic DNS propagation; no retry.',group:'DNS review',risk:'destructive',inputSchema:{...obj({...batchFields,preview_sha256:{type:'string',pattern:'^[0-9a-f]{64}$'},confirm:{type:'boolean'}},['preview_sha256']),$defs:batch.bodySchema.$defs},handler:async(a,c)=>{const p=await batchPlan(a,c);if(a.preview_sha256!==p.preview_sha256)throw new UsageError('Reviewed DNS batch changed: preview the exact zone/profile/body again.');return c.request('POST',p.path,[],p.body,a.account);}});
ALL_TOOLS.push({name:'analytics_query',title:'Read GraphQL analytics',description:'One parsed GraphQL query only, with variables. No mutations, subscriptions or multiple operations. Permissions, dataset retention, sampling and query limits remain provider controlled.',group:'Analytics',risk:'read',inputSchema:obj({query:{type:'string',minLength:1,maxLength:65536},variables:{type:'object'},account:{type:'string'}},['query']),handler:async(a,c)=>{if(Buffer.byteLength(a.query)>65536)throw new UsageError('GraphQL query exceeds the 64 KiB local cap.');let doc;try{doc=parse(a.query,{maxTokens:10000});}catch{throw new UsageError('Invalid or overly complex GraphQL query.');}const ops=doc.definitions.filter(x=>x.kind===Kind.OPERATION_DEFINITION);if(ops.length!==1||ops[0]!.operation!=='query'||doc.definitions.some(x=>x.kind!==Kind.OPERATION_DEFINITION&&x.kind!==Kind.FRAGMENT_DEFINITION))throw new UsageError('Provide exactly one GraphQL query; writes, subscriptions and schema definitions are refused.');return c.request('POST','/graphql',[],{query:a.query,variables:a.variables??{}},a.account);}});
for(const t of ALL_TOOLS)validators.set(t.name,ajv.compile(t.inputSchema));
export function validateArguments(t:ToolSpec,a:Json){check(validators.get(t.name)!,a);}
export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
